### ISSUE TITLE
for android how to configure apn parameter 

### ISSUE THREAD

**Issue by swapnaliDeveloper** [Pantrist-dev/capacitor-firebase-dynamic-links#15]
for android i m using only packageName , along with i need to use apn , but how to specify with plugin .
Also for ios ibi parameter

https://firebase.google.com/docs/dynamic-links/create-manually#parameters

**Comment by NLueg** [comment]
Hi there! Thank you for your question.
The `apn` corresponds to `androidParameters.packageName` while the `ibi` corresponds to `iosParameters.bundleId`.
I don't like to use the abbreviation for the config, that's why I use long term. You actually can see the mapping in the web plugin:

https://github.com/Pantrist-dev/capacitor-firebase-dynamic-links/blob/main/src/web.ts
